// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://conptaqatltdkuvsdyxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvbnB0YXFhdGx0ZGt1dnNkeXhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0OTM2MDQsImV4cCI6MjA1ODA2OTYwNH0.MuuA6xcI_LMEebtBdqNw0yWlvU1kbIN5RmFFc_vIV5g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);